### ISSUE TITLE
No error and no response generated in case of unsupported Content Type

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component#90]
## Steps to reproduce:
1. Configure REST API as following:

![image](https://user-images.githubusercontent.com/56208/69959300-1638d880-1507-11ea-9391-192964c47914.png)

with following URL `https://elasticio-local-agent.s3.eu-central-1.amazonaws.com/file-size-test/9mb.file.bin`

1. Generate sample

## Expected result

Error `Can not GET https://elasticio-local-agent.s3.eu-central-1.amazonaws.com/file-size-test/9mb.file.bin because content type "application/macbinary" not supported by the REST API component`

## Actual result

Nothing, after time-out just a time-out error not saying anything about not supported Content Type:

![image](https://user-images.githubusercontent.com/56208/69959656-f5bd4e00-1507-11ea-9c75-de1374269476.png)

**Comment by kirill-levitskiy** [comment]
There were several updates of the component and the platform since the issue was opened.
Current behavior differ from the described one. Now, the case can't be reproduced due to message-size limitations on the platform's side.
![image.png](https://images.zenhubusercontent.com/5b30db1002104679709f402e/5afa8d5e-12f6-4ce4-8f4f-665a123d35cb)

I performed tests with different sizes and MIME-types and all cases produce either empty message body, or some binary information, but with proper attachment at the sailor's storage.

Original file: `9mb.file.bin`, but from other hosting:
`"content-type":"application/octet-stream"`
![image.png](https://images.zenhubusercontent.com/5b30db1002104679709f402e/8e0d72af-e58e-4db5-acb9-c5913aa1bc73)

Trimmed part of original file: `100kb.file.bin`, from other hosting:
`"contentType":"multipart/form-data"`
![image.png](https://images.zenhubusercontent.com/5b30db1002104679709f402e/7b347b66-2488-4165-ae1a-5b8140913f74)



@zubairov could you upload a binary file with 100kB size for further experiments, please?
Even 1MB file produces the error: `Outgoing message size 16777516 exceeds limit of 10485760.`
The other problem, I can't create and upload a file with such MIME-type as `application/macbinary`.

**Comment by zubairov** [comment]
@kirill-levitskiy feel free to create any binary type it shouldn't have effect on behavior

**Comment by kirill-levitskiy** [comment]
@zubairov I can't reproduce similar behavior. I think, now we have a different one, because we added a limitation by message size into the sailor. Your case was too big for processing and you've got an error due to a message size, not a message type.

Should we throw an error, or just put the file into the attachments storage (steward) as is
Looks, now we process only specific set of MIME types as attachments. All "unknown" types we just wrap into the string:
https://github.com/elasticio/rest-api-component/blob/master/lib/utils.js#L497-L512 

Maybe, better to put into attachments storage all files except for `contType.includes('json')` or `contType.includes('xml')`?

I performed several tests with different binary MIME types, they confirmed component's code behavior:
`"contentType":"application/macbinary"`
![image](https://user-images.githubusercontent.com/40201204/76855096-0d230b80-6859-11ea-8f44-c40c2353f40e.png)

`"contentType":"application/x-binary"`
![image](https://user-images.githubusercontent.com/40201204/76855572-12cd2100-685a-11ea-9112-4c4dabab6201.png)

`"contentType":"application/octet-stream"`
![image](https://user-images.githubusercontent.com/40201204/76855755-76efe500-685a-11ea-9676-e4a3ac574626.png)
